### PR TITLE
ScalarWeightingClassifier: apply non-linear transformation

### PR DESCRIPTION
**Pull request by danieldk**
Note: this breaks compatibility with existing models, but I think that's acceptable, given that we have not made any models available.

Still training a model with these changes to gauge the improvement.

### CODE REVIEW

**Comment by danieldk** [comment]
Tested on Dutch. Gives the expected improvement on dependency parsing.

**Comment by twuebi** [comment]
The size of the non-linear projection is bound to the hidden size of the encoder?

**Review by DiveFish — APPROVED** [review]

**Comment by DiveFish** [comment]
Oh sorry, didn't refresh the tab and missed Tobi's comment.

**Comment by danieldk** [comment]
> The size of the non-linear projection is bound to the hidden size of the encoder?

That seemed like a sensible default. I am not married to it, though. I can add a constructor argument for the hidden size.

Though, then we have to decide what to do in `sticker2`, set it to the hidden size of the encoder or add per-layer configuration of the hidden size.

**Comment by twuebi** [comment]
I'd go for configurable, maybe as a global classifier hidden size instead of per classifier?

**Comment by danieldk** [comment]
> I'd go for configurable, maybe as a global classifier hidden size instead of per classifier?

Another hyperparameter to tune :/.

At any rate, I have fixed it here now, so at least `sticker-transformers` is flexible. Does it look ok now? I also added a test that just runs `forward` to verify that there are no shape errors.

**Comment by twuebi** [comment]
For me, 512 proved to be a sensible default. When moving to larger models it may be nice to control this part.

**Comment by danieldk** [comment]
> For me, 512 proved to be a sensible default. When moving to larger models it may be nice to control this part.

I think that this could be initially the hidden layer size in `sticker2` and we could make it a configurable option once it turns out that there is a large benefit. I am a bit hesitant to put too many options *now*, because I have to wrap my head around how to deal with configuration once we have various model types (e.g. BERT but with on-the-fly positional embeddings, ALBERT, etc.).

**Comment by twuebi** [comment]
Fine with me

**Review by twuebi — APPROVED** [review]

**Pull request merged**
